name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start Vite dev server
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload test report
        uses: actions/upload-artifact@8f57d64b323cfab1469e22c4e7a29fe3bc74a8f7
        with:
          name: cypress-report
          path: cypress/reports/mochawesome.html
