name: E2E Tests & Deploy Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Clean previous reports
        run: rm -rf cypress/reports/*

      - name: Start Vite dev server
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: |
          npx cypress run \
            --reporter cypress-mochawesome-reporter \
            --reporter-options reportDir=cypress/reports,overwrite=true,html=true,json=true

      - name: Show generated reports (debug)
        if: always()
        run: ls -R cypress/reports

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports